title: Service Layer
description: Library designed for SOA communication via REST with external services
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# SEO
url: https://profesia.github.io
baseurl: /service-layer

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: Architecture
    url: /architecture
  - title: Usage Guide
    url: /usage-guide

# Footer
github:
  repository_url: https://github.com/profesia/service-layer
